pluginManagement {
    includeBuild('../../paravoid-gradle-plugin')
    repositories { google(); mavenCentral(); gradlePluginPortal() }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories { google(); mavenCentral() }
}
rootProject.name = 'language-compatibility'
include ':paravoid-api', ':paravoid-runtime', ':probe-library'
project(':paravoid-api').projectDir = file('../../paravoid-api')
include ':paravoid-contract'
project(':paravoid-contract').projectDir = file('../../paravoid-contract')
project(':paravoid-runtime').projectDir = file('../../paravoid-runtime')

include ':paravoid-recovery-api'
project(':paravoid-recovery-api').projectDir = file('../../paravoid-recovery-api')
