pluginManagement {
    includeBuild('../../paravoid-gradle-plugin')
    includeBuild('../../paravoid-hilt')
    includeBuild('../../paravoid-work')
    repositories { google(); mavenCentral(); gradlePluginPortal() }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories { google(); mavenCentral() }
}
rootProject.name = 'hilt-work-compatibility'
include ':paravoid-api', ':paravoid-runtime'
project(':paravoid-api').projectDir = file('../../paravoid-api')
include ':paravoid-contract'
project(':paravoid-contract').projectDir = file('../../paravoid-contract')
project(':paravoid-runtime').projectDir = file('../../paravoid-runtime')

include ':paravoid-recovery-api'
project(':paravoid-recovery-api').projectDir = file('../../paravoid-recovery-api')

include ':paravoid-update-api'
project(':paravoid-update-api').projectDir = file('../../paravoid-update-api')
