plugins { id 'com.android.library' }
android {
    namespace 'com.lelloman.paravoidandroid.runtime'
    compileSdk 36
    sourceSets.main.java.srcDirs('../delivery/src', '../delivery/android/src')
    defaultConfig {
        minSdk 26
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}
dependencies {
    api project(':paravoid-api')
    implementation project(':paravoid-contract')
    testImplementation 'junit:junit:4.13.2'
}
