plugins { id 'groovy'; id 'java-gradle-plugin' }
group = 'com.lelloman.paravoid'
apply from: '../gradle/local-publication.gradle'
repositories { google(); mavenCentral() }
dependencies {
    implementation "com.lelloman.paravoid:paravoid-gradle-plugin:${project.version}"
    implementation 'org.ow2.asm:asm:9.7'
    testImplementation gradleTestKit()
    testImplementation 'junit:junit:4.13.2'
}
java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}
tasks.named('test') {
    systemProperty 'paravoid.repo', rootProject.projectDir.parentFile.absolutePath
    systemProperty 'paravoid.gradleUserHome', gradle.gradleUserHomeDir.absolutePath
}
gradlePlugin {
    plugins {
        paravoidWork {
            id = 'com.lelloman.paravoid.work'
            implementationClass = 'com.lelloman.paravoidandroid.work.gradle.ParavoidWorkPlugin'
        }
    }
}
